image:
  file: .gitpod.Dockerfile

# tasks:
#   - command: >
#       chmod +x envconfig.sh &&
#       ./envconfig.sh &&
#       export CONDA_PREFIX=/opt/conda

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - ms-vscode.cmake-tools@1.4.2:85XiRZZTNCh6JgvEqefqww==